apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: vault-databasing # same as policyName & roleName
  namespace: prod # for making k8-role in vault
  labels: 
    serviceAccountName: ""
spec:
  provider: vault
  parameters:
    vaultAddress: "http://vault.default:8200"
    roleName: "database"
    objects: |
      - objectName: "db-username1" 
        secretPath: "secret/data/dbname-1210"
        secretKey: "username-1"
      - objectName: "db-password-1"
        secretPath: "secret/data/dbname-12ddd10"
        secretKey: "password-1"
      - objectName: "dxb-usernamef-2"
        secretPath: "secret/datfda/dbnadme-233313"
        secretKey: "usernamed-2"
      - objectName: "db-password-3"
        secretPath: "secret/data/dbname-312"
        secretKey: "password-3"


