apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: vault_db_secret2 # same as policyName & roleName
  namespace: prod # for making k8-role in vault
  labels:
    serviceAccountName: "apps service account name"
    namespace: "apps namespace"
spec:
  provider: vault
  parameters:
    vaultAddress: "http://0.0.0.0:8200"
    roleName: "vault_db_role2 "
    vaultKubernetesMountPath: "kubernetes-testing"
    objects: |
      - objectName: "db-username1" 
        secretPath: "secret/data/DBcred"
        secretKey: "username-1"
      - objectName: "db-password-1"
        secretPath: "secret/data/DBcred"
        secretKey: "password-1"


