apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: vault_dbs-1 # same as policyName & roleName
  namespace: prod # for making k8-role in vault
  labels:
    serviceAccountName: "dummy-service-account-name"
    namespace: "alpha"
spec:
  provider: vault
  parameters:
    vaultAddress: "http://vault.default:8200"
    roleName: "test_role"
    vaultKubernetesMountPath: "kubernetes-testing"
    objects: |
      - objectName: "db-username1" 
        secretPath: "secret/data/DBcred"
        secretKey: "username-1"
      - objectName: "db-password-1"
        secretPath: "secret/data/DBcred"
        secretKey: "password-1"


