apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: vault-databasing # same as policyName & roleName
  namespace: prod # for making k8-role in vault
  labels: 
    serviceAccountName: ""

spec:
  provider: vault
  parameters:
    vaultAddress: "http://vault.default:8200"
    roleName: "database"
    objects: |
      - objectName: "db-username-1" 
        secretPath: "secret/data/dbname-1"
        secretKey: "username-1"
      - objectName: "db-password-1"
        secretPath: "secret/data/dbname-1"
        secretKey: "password-1"
      - objectName: "db-username-2"
        secretPath: "secret/data/dbname-2"
        secretKey: "username-2"
      - objectName: "db-password-3"
        secretPath: "secret/data/dbname-3"
        secretKey: "password-3"


