apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: dummy-app
  namespace: prod
  labels:
    namespace: prod
    serviceAccountName: dummy-sa
spec:
  provider: vault
  parameters:
    roleName: dummy-app_role
    vaultAddress: https://vault.eng.livspace.com
    vaultKubernetesMountPath: kubernetes-eks-messier
    objects: |
      - objectName: "db-pasword"
        secretKey: "db-password"
        secretPath: "secret/data/dummy-app/prod"
      - objectName: "db-username-65"
        secretKey: "db-username"
        secretPath: "secret/data/dummy-app/prod"
      - objectName: "some-other-secret"
        secretKey: "secretKey"
        secretPath: "secret/data/dummy-app/prod" 
