project: prod
host-catalog:
          name: service_23_
          description: nms_servicederpton/optio
          hosts:
              - name: nms_postgres_v6
                description: descri st_name /optional
                address: livspace-infra-postgres10.cluster-c8nvab78etai.ap-southeast-1.rds.amazonaws.com
                database_name: sqlpad
                username: livspace
                password: LivspaceRandomInfra12345
                default_port: 5432
                db_engine: postgresql