project: prod
host-catalog:
          name: NMS
          description: Notification Messaging service 1
          hosts:
              - name: nms_postgres_v100
                description: descri st_name /optional
                address: livspace-infra-postgres10.cluster-c8nvab78etai.ap-southeast-1.rds.amazonaws.com
                database_name: sqlpad
                username: livspace
                password: LivspaceRandomInfra12345
                default_port: 5432
                db_engine: postgresql
              - name: nms_postgres_v235
                description: descri st_name /optional
                address: livspace-infra-postgres10.cluster-c8nvab78etai.ap-southeast-1.rds.amazonaws.com
                database_name: sqlpad
                username: livspace
                password: LivspaceRandomInfra12345
                default_port: 5432
                db_engine: postgresql