patchCount: 2
host-catalog:
    name: NMS
    description: Notification Messaging service 1
    hosts:
      - name: nms_postgres_v55
        description: Dataase - sqlpad
        address: livspace-infra-postgres10.cluster-c8nvab78etai.ap-southeast-1.rds.amazonaws.com
        database_name: sqlpad
        username: livspace
        password: LivspaceRandomInfra12345
        default_port: 5432
        db_engine: postgresql
        engineering_grants:
            on:
            - "batches"
            - "cache"
            - "connections"
      - name: nms_postgres_v009
        description: Database - sqlpad
        address: livspace-infra-postgres10.cluster-c8nvab78etai.ap-southeast-1.rds.amazonaws.com
        database_name: sqlpad
        username: livspace
        password: LivspaceRandomInfra12345
        default_port: 5432
        db_engine: postgresql
        engineering_grants:
            on:
            - "all tables in schema public"
