project: prod
host-catalog:
          name: service_23_
          description: nms_servicederpton/optio
          host-sets:
                - name: nms_1_postgres_591_set
                  description: descrmicroervice_2 /optional
                  target:
                      name: nms_1_postgres_591_target
                      description: dedede
                      default_port: 5432
                  hosts:
                      name: nms_1_postgres_591
                      description: descri st_name_2 /optional
                      address: livspace-infra-postgres10.cluster-c8nvab78etai.ap-southeast-1.rds.amazonaws.com
                      database_name: sqlpad
                      username: livspace
                      password: LivspaceRandomInfra12345