name: GitHub Actions Demo
run-name: Add targets in boundary
on: push
jobs:  
  build:
    runs-on: self-hosted
    name: Put targets on boundary
    steps:
      - uses: chrisdickinson/setup-yq@latest
      - uses: sergeysova/jq-action@v2
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 
      - name: Get changed files in the docs folder
        id: changed-files-specific
        uses: tj-actions/changed-files@v34
        with:
          files: |
            Vault-secrets/vault_secrets/**
      # - name: Run step if any file(s) in the Vault-secret folder change
      #   if: steps.changed-files-specific.outputs.any_changed == 'true'
      #   run: |
      #     for file in ${{ steps.changed-files-specific.outputs.all_changed_files }} ; do 
      #       yq -o=json $file
      #     done
      # Prints the changes when done / added - Git Actions does not run when file is removed ******
      - name: Run this to read files changed in spc-yaml
        run: |
            echo "{\"command\":\"login\",\"token_type\":null,\"attributes\":{\"login_name\":\"admin\",\"password\":\"password\"}}" > payload.json
            curl --request POST --data @payload.json http://boundary-release.default:9200/v1/auth-methods/ampw_mfA94ktoY8:authenticate > response.json
            token=$(jq -r '.attributes.token' response.json)
            echo $token
            host-catalog-name="nms"
            host-catalog-description="nms description"
            echo "{\"type\":\"static\",\"name\":\"${host-catalog-name}\",\"description\":\"${host-catalog-description}\",\"scope_id\":\"p_uz5ahCZ4XZ\"}" > host-catalog.json
            curl --header 'Authorization: Bearer ${token}' --request POST --data @host-catalog.json http://boundary-release.default:9200/v1/host-catalogs
            rm -f payload.json response.json
            
        
          

