name: Vault-token create
run-name: Vault-token recreate
on: push
jobs:  
  build:
    runs-on: self-hosted
    name: Replace vault token with new one
    steps:
      - uses: chrisdickinson/setup-yq@latest
      - uses: sergeysova/jq-action@v2
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 
      
      - name: Run this to read files changed in spc-yaml
        run: |
            curl --header "X-Vault-Token: ${{ secrets.VAULT_CREATE_TOKEN }}" --request POST http://vault.default:8200/v1/auth/token/renew-self
            
            

            
        
          

