name: GitHub Actions Demo
run-name: Put KV secrets in vault
on: push
jobs:  
  build:
    runs-on: self-hosted
    name: KV secrets
    steps:
      - uses: chrisdickinson/setup-yq@latest
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 
      - name: Get changed files in the docs folder
        id: changed-files-specific
        uses: tj-actions/changed-files@v34
        with:
          files: |
            Vault-secrets/vault_secrets/**
      # - name: Run step if any file(s) in the Vault-secret folder change
      #   if: steps.changed-files-specific.outputs.any_changed == 'true'
      #   run: |
      #     for file in ${{ steps.changed-files-specific.outputs.all_changed_files }} ; do 
      #       yq -o=json $file
      #     done
      # Prints the changes when done / added - Git Actions does not run when file is removed ******
      - name: Run this to read files changed in spc-yaml
        run: |
            for val in ${{ steps.changed-files-specific.outputs.all_changed_files }} ;
            do 
              path=$(yq r $val "path")
              curl --header "X-Vault-Token:hvs.dVhfoKNLQ461fo2L78dKKGkh" --request POST --data '{"data":{"k1":"v1"}}' http://vault.default:8200/v1/secret/data/$path
              rm -f payload.json
            done
        
          

